server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: hv-conifgserver
  rabbitmq:
    host: 10.60.25.178
    port: 5672
    username: admin
    password: admin
    virtual-host: my_vhost
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: http://10.60.253.36/hv/houmourv.git
          search-paths:
            - config
          username: humour
          password: 123456789
management:
  endpoints:
    web:
      exposure:
        include: "*"